CREATE TABLE "authors" (
	"emp_id" integer NOT NULL,
	"paper_id" integer NOT NULL,
	"is_lead_author" boolean NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "author_id" PRIMARY KEY("emp_id","paper_id")
);
--> statement-breakpoint
CREATE TABLE "journal_Issue" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "journal_Issue_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"publication_date" date NOT NULL,
	"title" text NOT NULL,
	"format" text NOT NULL,
	"emp_id" integer NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "lab_Equipment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lab_Equipment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"Primary_Callibration_Standard" text NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "office" (
	"id" text PRIMARY KEY NOT NULL,
	"address" text NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "research_paper" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "research_paper_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"volume_identifier" integer NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "researchers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "researchers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"phone_extension" text NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "skilled" (
	"emp_id" integer NOT NULL,
	"item_no" integer NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "skill_id" PRIMARY KEY("emp_id","item_no")
);
--> statement-breakpoint
ALTER TABLE "authors" ADD CONSTRAINT "authors_emp_id_researchers_id_fk" FOREIGN KEY ("emp_id") REFERENCES "public"."researchers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "authors" ADD CONSTRAINT "authors_paper_id_research_paper_id_fk" FOREIGN KEY ("paper_id") REFERENCES "public"."research_paper"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "journal_Issue" ADD CONSTRAINT "journal_Issue_emp_id_researchers_id_fk" FOREIGN KEY ("emp_id") REFERENCES "public"."researchers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "research_paper" ADD CONSTRAINT "research_paper_volume_identifier_journal_Issue_id_fk" FOREIGN KEY ("volume_identifier") REFERENCES "public"."journal_Issue"("id") ON DELETE null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "researchers" ADD CONSTRAINT "researchers_phone_extension_office_id_fk" FOREIGN KEY ("phone_extension") REFERENCES "public"."office"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "skilled" ADD CONSTRAINT "skilled_emp_id_researchers_id_fk" FOREIGN KEY ("emp_id") REFERENCES "public"."researchers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "skilled" ADD CONSTRAINT "skilled_item_no_lab_Equipment_id_fk" FOREIGN KEY ("item_no") REFERENCES "public"."lab_Equipment"("id") ON DELETE cascade ON UPDATE no action;